server:
  port: 9080
  servlet:
    context-path: /microcredito/api/v1

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    blobVar: progressiveStreaming=2;
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
    properties:
      hibernate: